=== sergeik66/projects-demo-zone/dataset_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Platform Services Ingest Dataset",
    "description": "A dataset that represents source data to be ingested",
    "type": "object",
    "properties": {
        "datasetName": {
            "type": "string"
        },
        "enable": {
            "type": "boolean"
        },
        "datasetTypeName": {
            "$ref": "enums.json#/definitions/datasetTypeName"
        },
        "databaseName": {
            "type": "string"
        },
        "datasetSchema": {
            "type": "string"
        },
        "skipCuratedLoad": {
            "type": "boolean"
        },
        "fileType": {
            "$ref": "enums.json#/definitions/fileType"
        },
        "sourceSystemProperties": {
            "oneOf": [
                {
                    "if": {
                        "properties": {
                            "datasetTypeName": {
                                "const": "database"
                            }
                        }
                    },
                    "then": {
                        "$ref": "sourceSystemProperties.json#/definitions/database"
                    }
                },
                {
                    "if": {
                        "properties": {
                            "datasetTypeName": {
                                "const": "file"
                            }
                        }
                    },
                    "then": {
                        "$ref": "sourceSystemProperties.json#/definitions/file"
                    }
                }
            ]
        },
        "rawProperties": {
            "$ref": "rawProperties.json#/rawProperties"
        },
        "curatedProperties": {
            "$ref": "curatedProperties.json#/curatedProperties"
        },
        "customProperties": {
            "type": "object"
        }
    },
    "required": [
        "datasetName",
        "enable",
        "datasetTypeName",
        "sourceSystemProperties",
        "rawProperties",
        "curatedProperties"
    ],
    "allOf": [
        {
            "if": {
                "properties": {
                    "datasetTypeName": {
                        "const": "database"
                    }
                }
            },
            "then": {
                "required": [
                    "databaseName",
                    "datasetSchema"
                ]
            }
        },
        {
            "$ref": "curatedProperties.json#/definitions/fileTypeCsv"
        },
        {
            "$ref": "curatedProperties.json#/definitions/fileTypeExcel"
        }
    ]
}

=== sergeik66/projects-demo-zone/dataset.json
{
    "datasetName": "wcpayrol",
    "enable": true,
    "datasetTypeName": "database",
    "databaseName": "GIGEOMDATA",
    "datasetSchema": "dbo",
    "sourceSystemProperties": {
        "sourceSystemName": "demo_sqldb",
        "includeSpecificColumns": [
            "code",
            "primeseq",
            "state",
            "effdate",
            "classcode",
            "seqcode",
            "territory",
            "exmod",
            "minprem",
            "exposure",
            "premium",
            "rate",
            "xcluamt",
            "losscons",
            "form",
            "paragraph",
            "volcomp",
            "hazard",
            "cvrg",
            "disctype",
            "classuffix",
            "diffprem",
            "diffrate",
            "rateeffdate",
            "losscost"
        ],
        "ingestType": "cdc",
        "isDynamicQuery": true
    },
    "rawProperties": {
        "lakehouseName": "den_lhw_pdi_001_raw",
        "fileType": "parquet",
        "directoryName": "demo_sqldb"
    },
    "curatedProperties": {
        "lakehouseName": "den_lhw_pdi_001_curated",
        "schemaName": "demo",
        "fileOptions": {
            "encoding": "ISO-8859-1",
            "header": true,
            "inferColumnTypes": true,
            "multiline": true,
            "delimiter": ",",
            "escape": "\"",
            "timestampFormat": "dd/MM/yyyy"
        },
        "columnList": ["*"],
        "primaryKeyList": [
            "code",
            "primeseq",
            "state",
            "effdate",
            "classcode",
            "seqcode",
            "territory",
            "rateeffdate",
            "volcomp"
        ],
        "duplicateCheckEnabled": false,
        "targetFileFormat": "delta",
        "targetLoadType": "merge"
    }
}
